import type { Metadata } from "next";
import "./globals.css";
import { ThirdwebProvider } from "thirdweb/react";


// I need to bring this client everywhere in the page
import { client } from "../components/server-sided/thirdweb/client";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  // THIS WILL BE WHERE OUR PROVIDERS WILL BE or maybe make an app page?
  return (
    <ThirdwebProvider>
    
      <html lang="en">
        <body className="bg-white">
          {children}
        </body>
      </html>

    </ThirdwebProvider>
  );
}
